-- ========================================================================
-- SKRIP RESET TOTAL & PEMBUATAN SKEMA BARU SUPABASE (FRESH SETUP)
-- ========================================================================
-- CARA PENGGUNAAN:
-- 1. Buka Supabase Dashboard (https://supabase.com/dashboard)
-- 2. Pilih Project Anda
-- 3. Buka menu "SQL Editor" di bilah sisi kiri
-- 4. Klik "New Query", salin SEMUA kode di bawah ini dan tempel (paste)
-- 5. Klik tombol "Run" di pojok kanan bawah
-- ========================================================================

-- STEP 1: HAPUS TABEL LAMA JIKA ADA (CLEAN RESET)
DROP TABLE IF EXISTS public.sale_items CASCADE;
DROP TABLE IF EXISTS public.sales CASCADE;
DROP TABLE IF EXISTS public.purchase_items CASCADE;
DROP TABLE IF EXISTS public.purchases CASCADE;
DROP TABLE IF EXISTS public.stock_movement_logs CASCADE;
DROP TABLE IF EXISTS public.items CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

-- ========================================================================
-- STEP 2: BUAT ULANG TABEL-TABEL SECARA LENGKAP & FRESH
-- ========================================================================

-- 1. Tabel Profil Pengguna (Users)
CREATE TABLE public.users (
    id TEXT PRIMARY KEY,
    username TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'KASIR', -- 'OWNER', 'ADMIN', 'KASIR'
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Tabel Master Barang / Sparepart (Items)
CREATE TABLE public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT DEFAULT 'Umum',
    buy_price NUMERIC(15, 2) DEFAULT 0,
    sell_price NUMERIC(15, 2) DEFAULT 0,
    min_stock INT DEFAULT 0,
    current_stock INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Tabel Master Pelanggan (Customers)
CREATE TABLE public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    address TEXT DEFAULT '',
    total_debt NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Tabel Master Pemasok (Suppliers)
CREATE TABLE public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    address TEXT DEFAULT '',
    total_payable NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Tabel Transaksi Penjualan Header (Sales)
CREATE TABLE public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT,
    customer_name TEXT DEFAULT 'Pelanggan Umum',
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payment_status TEXT NOT NULL DEFAULT 'LUNAS', -- 'LUNAS' / 'HUTANG'
    grand_total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    remaining_debt NUMERIC(15, 2) NOT NULL DEFAULT 0,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. Tabel Detail Item Penjualan (Sale Items)
CREATE TABLE public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL,
    item_id BIGINT,
    part_number TEXT DEFAULT '',
    item_name TEXT DEFAULT '',
    qty INT NOT NULL DEFAULT 1,
    price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. Tabel Transaksi Pembelian Header (Purchases)
CREATE TABLE public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT UNIQUE NOT NULL,
    supplier_id BIGINT,
    supplier_name TEXT DEFAULT 'Supplier',
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payment_status TEXT NOT NULL DEFAULT 'LUNAS', -- 'LUNAS' / 'HUTANG'
    grand_total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    remaining_payable NUMERIC(15, 2) NOT NULL DEFAULT 0,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. Tabel Detail Item Pembelian (Purchase Items)
CREATE TABLE public.purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT NOT NULL,
    item_id BIGINT,
    part_number TEXT DEFAULT '',
    item_name TEXT DEFAULT '',
    qty INT NOT NULL DEFAULT 1,
    price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 9. Tabel Log Riwayat Pergerakan Stok (Stock Movement Logs)
CREATE TABLE public.stock_movement_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT,
    part_number TEXT DEFAULT '',
    item_name TEXT DEFAULT '',
    change_qty INT NOT NULL,
    movement_type TEXT NOT NULL, -- 'SALE', 'PURCHASE', 'ADJUSTMENT'
    reference_number TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ========================================================================
-- STEP 3: NONAKTIFKAN ROW LEVEL SECURITY (RLS) UNTUK MODE SYNC
-- ========================================================================
ALTER TABLE public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movement_logs DISABLE ROW LEVEL SECURITY;

-- ========================================================================
-- STEP 4: RELOAD SCHEMA CACHE POSTGREST
-- ========================================================================
NOTIFY pgrst, 'reload schema';
