-- ========================================================================
-- SKRIP MIGRASI / PERBAIKAN KOLOM DATABASE SUPABASE
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- Skrip ini AMAN dijalankan berulang kali (tidak akan menghapus data yang ada).
-- ========================================================================

-- 1. Pastikan Tabel Items lengkap
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_number TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category TEXT DEFAULT 'Umum',
    buy_price NUMERIC(15, 2) DEFAULT 0,
    sell_price NUMERIC(15, 2) DEFAULT 0,
    min_stock INT DEFAULT 0,
    current_stock INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Pastikan Tabel Customers lengkap
CREATE TABLE IF NOT EXISTS public.customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    address TEXT DEFAULT '',
    total_debt NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Pastikan Tabel Suppliers lengkap
CREATE TABLE IF NOT EXISTS public.suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    phone TEXT UNIQUE NOT NULL,
    address TEXT DEFAULT '',
    total_payable NUMERIC(15, 2) DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Pastikan Tabel Sales (Penjualan)
CREATE TABLE IF NOT EXISTS public.sales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    customer_id BIGINT,
    customer_name TEXT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payment_status TEXT NOT NULL DEFAULT 'LUNAS',
    grand_total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    remaining_debt NUMERIC(15, 2) NOT NULL DEFAULT 0,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tambahkan kolom jika tabel sales sudah terlanjur ada sebelumnya
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_id BIGINT;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS customer_name TEXT;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS remaining_debt NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(15, 2) DEFAULT 0;

-- 5. Pastikan Tabel Sale Items (Detail Penjualan)
CREATE TABLE IF NOT EXISTS public.sale_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT NOT NULL,
    item_id BIGINT,
    part_number TEXT,
    item_name TEXT,
    qty INT NOT NULL DEFAULT 1,
    price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS invoice_number TEXT;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS item_id BIGINT;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS part_number TEXT;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS item_name TEXT;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS qty INT DEFAULT 1;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS price NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS subtotal NUMERIC(15, 2) DEFAULT 0;

-- 6. Pastikan Tabel Purchases (Pembelian)
CREATE TABLE IF NOT EXISTS public.purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT UNIQUE NOT NULL,
    supplier_id BIGINT,
    supplier_name TEXT,
    date TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    payment_status TEXT NOT NULL DEFAULT 'LUNAS',
    grand_total NUMERIC(15, 2) NOT NULL DEFAULT 0,
    paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0,
    remaining_payable NUMERIC(15, 2) NOT NULL DEFAULT 0,
    due_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS supplier_id BIGINT;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS supplier_name TEXT;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS due_date TIMESTAMPTZ;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS remaining_payable NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE public.purchases ADD COLUMN IF NOT EXISTS paid_amount NUMERIC(15, 2) DEFAULT 0;

-- 7. Pastikan Tabel Purchase Items (Detail Pembelian)
CREATE TABLE IF NOT EXISTS public.purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    po_number TEXT NOT NULL,
    item_id BIGINT,
    part_number TEXT,
    item_name TEXT,
    qty INT NOT NULL DEFAULT 1,
    price NUMERIC(15, 2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(15, 2) NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS po_number TEXT;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS item_id BIGINT;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS part_number TEXT;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS item_name TEXT;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS qty INT DEFAULT 1;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS price NUMERIC(15, 2) DEFAULT 0;
ALTER TABLE public.purchase_items ADD COLUMN IF NOT EXISTS subtotal NUMERIC(15, 2) DEFAULT 0;

-- 8. Pastikan Tabel Stock Movement Logs
CREATE TABLE IF NOT EXISTS public.stock_movement_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT,
    part_number TEXT,
    item_name TEXT,
    change_qty INT NOT NULL,
    movement_type TEXT NOT NULL, -- 'SALE', 'PURCHASE', 'ADJUSTMENT'
    reference_number TEXT NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Lengkapi kolom stock_movement_logs jika sebelumnya belum ada
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS part_number TEXT;
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS item_name TEXT;
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS item_id BIGINT;
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS change_qty INT DEFAULT 0;
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS movement_type TEXT;
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS reference_number TEXT;
ALTER TABLE public.stock_movement_logs ADD COLUMN IF NOT EXISTS timestamp TIMESTAMPTZ DEFAULT NOW();

-- 9. Matikan RLS untuk kemudahan sinkronisasi
ALTER TABLE public.items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.customers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.suppliers DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sales DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.sale_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchases DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.purchase_items DISABLE ROW LEVEL SECURITY;
ALTER TABLE public.stock_movement_logs DISABLE ROW LEVEL SECURITY;

-- 10. Refresh Cache Schema PostgREST Supabase
NOTIFY pgrst, 'reload schema';
